global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
  - job_name: "Zeek"
    scrape_interval: 500ms
    static_configs:
    - targets: ["172.16.3.4:4040",  # logger
                "172.16.3.4:4041",  # manager
                "172.16.3.4:4042",  # proxy
                "172.16.3.4:4051",  # worker 1
                "172.16.3.4:4052",  # worker 2
                "172.16.3.4:4053",  # worker 3
                "172.16.3.4:4054",  # worker 4
                "172.16.3.4:4055",  # worker 5
                "172.16.3.4:4056",  # worker 6
                "172.16.3.4:4057",  # worker 7
                "172.16.3.4:4058"]  # worker 8
