version: '3.9'

networks:
  zeek-builder:
    ipam:
      driver: default
      config:
        - subnet: "172.16.3.0/24"

# These are created with
# docker volume create --driver local \
#    --opt type=none \
#    --opt device=/path/to/data \
#    --opt o=bind volume_name
volumes:
  zeek_logs:
    external: true

services:

  builder:
    container_name: builder
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./configs:/benchmark/configs:ro
      - ./scripts:/benchmark/scripts:ro
      - zeek_logs:/benchmark/zeek_logs
    working_dir: /benchmark
    command: /benchmark/scripts/build.sh
    networks:
      zeek-builder:
        ipv4_address: 172.16.3.4
    expose:
      - 4040-4042/tcp
      - 4051-4058/tcp
