version: '3.9'

networks:
  zeek-builder:
    ipam:
      driver: default
      config:
        - subnet: "172.16.3.0/24"

# These are created with
# docker volume create --driver local \
#    --opt type=none \
#    --opt device=/path/to/data \
#    --opt o=bind volume_name
volumes:
  prometheus_data:
    external: true
  grafana_data:
    external: true
  zeek_logs:
    external: true

services:

  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=26w'
    restart: unless-stopped
    networks:
      zeek-builder:
        ipv4_address: 172.16.3.2
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_USERS_ALLOW_SIGNUP=false
    restart: unless-stopped
    networks:
      zeek-builder:
        ipv4_address: 172.16.3.3
    ports:
      - 3000:3000

  builder:
    container_name: builder
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./configs:/benchmark/configs:ro
      - ./scripts:/benchmark/scripts:ro
      - zeek_logs:/benchmark/zeek_logs
    working_dir: /benchmark
    command: /benchmark/scripts/build.sh
    networks:
      zeek-builder:
        ipv4_address: 172.16.3.4
    expose:
      - 4040-4042/tcp
      - 4051-4058/tcp
